using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Runtime.Serialization;
using Microsoft.PowerShell;
using Microsoft.PowerShell.Commands;

namespace PSADT.UserInterface.DialogOptions
{
    /// <summary>
    /// Options for all dialogs.
    /// </summary>
    [DataContract]
    public sealed record HelpConsoleOptions : IDialogOptions
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpConsoleOptions"/> class with the specified options.
        /// This accepts a hashtable of parameters to ease construction on the PowerShell side of things.
        /// </summary>
        /// <param name="options"></param>
        public HelpConsoleOptions(Hashtable options) : this(
            (options ?? throw new ArgumentNullException(nameof(options)))["ExecutionPolicy"] as ExecutionPolicy? ?? (ExecutionPolicy)(-1),
            options["Modules"] is IReadOnlyList<ModuleSpecification> modules ? new ReadOnlyCollection<Hashtable>([.. modules.Select(static m => new Hashtable { { "ModuleName", m.Name }, { "ModuleVersion", m.Version?.ToString() }, { "Guid", m.Guid } })]) : null!)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HelpConsoleOptions"/> class with the specified execution policy
        /// and module data.
        /// </summary>
        /// <param name="executionPolicy">The execution policy to be applied. This determines the level of permissions granted during execution.</param>
        /// <param name="moduleData">A read-only collection of hashtables containing module-specific data. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="moduleData"/> is null.</exception>
        private HelpConsoleOptions(ExecutionPolicy executionPolicy, ReadOnlyCollection<Hashtable> moduleData)
        {
            if ((int)executionPolicy == -1)
            {
                throw new ArgumentNullException(nameof(executionPolicy), "ExecutionPolicy value is null or invalid.");
            }
            if (moduleData is null || moduleData.Count == 0 || moduleData.Any(static m => m["ModuleName"] is not string name || string.IsNullOrWhiteSpace(name) || m["Guid"] is null || m["ModuleVersion"] is null))
            {
                throw new ArgumentNullException(nameof(moduleData), "Modules value is null or invalid.");
            }
            ExecutionPolicy = executionPolicy;
            ModuleData = moduleData;
        }

        /// <summary>
        /// Gets the execution policy that determines how operations are executed.
        /// </summary>
        [DataMember]
        public ExecutionPolicy ExecutionPolicy { get; private set; }

        /// <summary>
        /// Gets a read-only list of module specifications derived from the current module data.
        /// </summary>
        /// <remarks>The list is generated by transforming the internal module data into <see
        /// cref="ModuleSpecification"/> instances. This property provides a snapshot of the module specifications at
        /// the time of access.</remarks>
        [IgnoreDataMember]
        public IReadOnlyList<ModuleSpecification> Modules => new ReadOnlyCollection<ModuleSpecification>([.. ModuleData.Select(static m => new ModuleSpecification(m))]);

        /// <summary>
        /// Represents a collection of module data.
        /// </summary>
        /// <remarks>This collection is read-only and contains elements of type <see cref="Hashtable"/>.</remarks>
        [DataMember]
        private ReadOnlyCollection<Hashtable> ModuleData { get; set; }
    }
}
