<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <Product>PSAppDeployToolkit Win32 Native Methods Library</Product>
    <AssemblyTitle>PSAppDeployToolkit Win32 Native Methods Library</AssemblyTitle>
    <AssemblyDescription>This assembly provides Win32 library access to all areas of PSAppDeployToolkit.</AssemblyDescription>
    <NoWarn>SYSLIB1045;SYSLIB1054</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PSADT" />
    <InternalsVisibleTo Include="PSADT.ClientServer.Client" />
    <InternalsVisibleTo Include="PSADT.ClientServer.Client.Compatible" />
    <InternalsVisibleTo Include="PSADT.ClientServer.Client.Launcher" />
    <InternalsVisibleTo Include="PSADT.ClientServer.Client.Launcher.Compatible" />
    <InternalsVisibleTo Include="PSADT.ClientServer.Server" />
    <InternalsVisibleTo Include="PSADT.Interop.Tests" />
    <InternalsVisibleTo Include="PSADT.UserInterface" />
    <InternalsVisibleTo Include="PSADT.UserInterface.Interfaces" />
    <InternalsVisibleTo Include="PSADT.UserInterface.Interfaces.TestHarness" />
    <InternalsVisibleTo Include="PSADT.WindowsRuntime" />
    <InternalsVisibleTo Include="PSAppDeployToolkit" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Linq.AsyncEnumerable" />
  </ItemGroup>

  <PropertyGroup>
    <MeziantouPolyfill_IncludedPolyfills>
      M:System.ArgumentException.ThrowIfNullOrWhiteSpace|
      M:System.ArgumentNullException.ThrowIfNull(System.Object,|
      M:System.ArgumentNullException.ThrowIfNull(System.Void|
      M:System.ArgumentOutOfRangeException.ThrowIfGreaterThan`|
      M:System.ArgumentOutOfRangeException.ThrowIfLessThan`|
      M:System.ArgumentOutOfRangeException.ThrowIfNegative`|
      M:System.ArgumentOutOfRangeException.ThrowIfNegativeOrZero`|
      M:System.ArgumentOutOfRangeException.ThrowIfNotEqual`|
      M:System.ArgumentOutOfRangeException.ThrowIfZero`|
      M:System.Diagnostics.Process.WaitForExitAsync|
      M:System.Int32.TryParse(System.ReadOnlySpan{System.Char},System.IFormatProvider,|
      M:System.IO.Path.IsPathFullyQualified|
      M:System.IO.Path.Join|
      M:System.IO.StreamReader.ReadLineAsync|
      M:System.Nullable.GetValueRefOrDefaultRef|
      M:System.ObjectDisposedException.ThrowIf(System.Boolean,System.Object)|
      M:System.String.Contains(System.Char,System.StringComparison)|
      M:System.String.CopyTo|
      M:System.String.Create|
      M:System.String.EndsWith(System.Char)|
      M:System.String.GetHashCode(System.StringComparison)|
      M:System.String.IndexOf(System.Char,System.StringComparison)|
      M:System.String.Join(System.Char,System.String[])|
      M:System.String.Join`|
      M:System.String.Replace(System.String,System.String,System.StringComparison)|
      M:System.String.StartsWith(System.Char)|
      M:System.String.TryCopyTo|
      M:System.StringComparer.FromComparison|
      M:System.Threading.CancellationTokenSource.CancelAsync|
      M:System.Threading.Tasks.Task.WaitAsync(System.Threading.CancellationToken)|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Diagnostics.StackTraceHiddenAttribute|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
      T:System.Runtime.CompilerServices.DefaultInterpolatedStringHandler|
      T:System.Runtime.CompilerServices.InterpolatedStringHandlerArgumentAttribute|
      T:System.Runtime.CompilerServices.InterpolatedStringHandlerAttribute|
      T:System.Runtime.CompilerServices.ModuleInitializerAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
    <DefineConstants>$(DefineConstants);MEZIANTOU_POLYFILL_SKIP_MICROSOFT_CODEANALYSIS_EMBEDDEDATTRIBUTE</DefineConstants>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
</Project>
