<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Invoke-AppDeployToolkit</AssemblyName>
    <Product>PSAppDeployToolkit Deployment Script Launcher</Product>
    <AssemblyTitle>PSAppDeployToolkit Deployment Script Launcher</AssemblyTitle>
    <AssemblyDescription>Launches a PSAppDeployToolkit Invoke-AppDeployToolkit.ps1 script without a PowerShell console window being visible.</AssemblyDescription>
    <ApplicationIcon>Properties\appIcon.ico</ApplicationIcon>
    <StartupObject>PSADT.Invoke.Program</StartupObject>
    <NoWarn>CA1303;PInvoke009</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PSADT.Invoke.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <MeziantouPolyfill_IncludedPolyfills>
      M:System.IO.Path.Join|
    </MeziantouPolyfill_IncludedPolyfills>
    <DefineConstants>$(DefineConstants);MEZIANTOU_POLYFILL_SKIP_MICROSOFT_CODEANALYSIS_EMBEDDEDATTRIBUTE</DefineConstants>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
</Project>
