/*
 * Copyright 2026 Dan Cunningham
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Linq;

namespace Fluence.Wpf.Demo.Mvvm.ViewModels
{
    /// <summary>
    /// Root ViewModel for the Task Manager window. Demonstrates:
    /// <list type="bullet">
    ///   <item><description><c>[ObservableProperty]</c> - backing fields with auto-notification</description></item>
    ///   <item><description><c>[RelayCommand(CanExecute)]</c> - enabled/disabled command binding</description></item>
    ///   <item><description><c>partial void OnXxxChanged</c> - source-generated change callbacks</description></item>
    ///   <item><description><c>ObservableCollection</c> - live-updating list</description></item>
    ///   <item><description>Derived properties via <c>OnPropertyChanged</c></description></item>
    /// </list>
    /// </summary>
    public partial class MainViewModel : ObservableObject
    {
        // The full unfiltered source list - never bound to directly.
        private readonly ObservableCollection<TaskItemViewModel> _allTasks = [];

        // ---------------------------------------------------------------
        // Observable properties (source-generated by CommunityToolkit.Mvvm)
        // ---------------------------------------------------------------

        /// <summary>
        /// The filtered view of tasks that the ListView binds to.
        /// Rebuilt by <see cref="Refresh"/> whenever tasks or filter change.
        /// </summary>
        [ObservableProperty]
        private ObservableCollection<TaskItemViewModel> _displayedTasks = [];

        /// <summary>
        /// Text the user types for a new task. Two-way bound to the TextBox.
        /// The <c>OnNewTaskTextChanged</c> callback re-evaluates <see cref="AddCommand"/>.
        /// </summary>
        [ObservableProperty]
        private string _newTaskText = string.Empty;

        /// <summary>
        /// Current filter selection. Changing it triggers <c>OnActiveFilterChanged</c>
        /// which calls <see cref="Refresh"/>. <see cref="Refresh"/> itself raises
        /// <see cref="StatusText"/> and <see cref="ProgressValue"/> notifications after
        /// rebuilding <see cref="DisplayedTasks"/>, so the data is always current when
        /// bindings re-read those properties. Do NOT add [NotifyPropertyChangedFor] here -
        /// that would fire the notifications before DisplayedTasks is rebuilt (stale read).
        /// </summary>
        [ObservableProperty]
        private FilterMode _activeFilter = FilterMode.All;

        // ---------------------------------------------------------------
        // Derived / computed properties
        // ---------------------------------------------------------------

        /// <summary>
        /// Human-readable task completion summary shown in the footer.
        /// </summary>
        public string StatusText
        {
            get
            {
                int total = _allTasks.Count; int done = _allTasks.Count(t => t.IsCompleted);
                return total == 0 ? "No tasks" : string.Format(CultureInfo.CurrentCulture, "{0} of {1} completed", done, total);
            }
        }

        /// <summary>
        /// Progress bar value 0-100 based on completion ratio.
        /// </summary>
        public double ProgressValue => _allTasks.Count != 0
            ? (double)_allTasks.Count(t => t.IsCompleted) / _allTasks.Count * 100
            : 0;

        // ---------------------------------------------------------------
        // Constructor
        // ---------------------------------------------------------------

        /// <summary>
        /// Seeds a few sample tasks so the app is useful on first run and the XAML designer shows
        /// realistic rows. New items are wired to <see cref="OnItemPropertyChanged"/> exactly like
        /// <see cref="Add"/> does, so toggling completion refreshes the filtered view and the footer.
        /// </summary>
        public MainViewModel()
        {
            Seed("Try the Fluence.Wpf MVVM demo", isCompleted: true);
            Seed("Toggle a task to see the strikethrough + progress update", isCompleted: false);
            Seed("Filter by All / Pending / Completed", isCompleted: false);
            Seed("Add your own task below", isCompleted: false);
            Refresh();
        }

        private void Seed(string title, bool isCompleted)
        {
            TaskItemViewModel item = new(title) { IsCompleted = isCompleted };
            item.PropertyChanged += OnItemPropertyChanged;
            _allTasks.Add(item);
        }

        // ---------------------------------------------------------------
        // Commands
        // ---------------------------------------------------------------

        /// <summary>
        /// Adds a new task from <see cref="NewTaskText"/>.
        /// Disabled (grayed out) when the text box is blank - CanExecute is
        /// re-evaluated every time <see cref="NewTaskText"/> changes via
        /// OnNewTaskTextChanged.
        /// </summary>
        [RelayCommand(CanExecute = nameof(CanAdd))]
        private void Add()
        {
            TaskItemViewModel item = new(NewTaskText.Trim());
            // Subscribe so completion toggles trigger a filter refresh.
            item.PropertyChanged += OnItemPropertyChanged;
            _allTasks.Add(item);
            NewTaskText = string.Empty;
            Refresh();
        }

        private bool CanAdd()
        {
            return !string.IsNullOrWhiteSpace(NewTaskText);
        }

        // Source-generated partial callback - fires after NewTaskText setter runs.
        partial void OnNewTaskTextChanged(string value)
        {
            AddCommand.NotifyCanExecuteChanged();
        }

        /// <summary>
        /// Removes a specific task. Bound in the DataTemplate via
        /// <c>RelativeSource AncestorType=Window</c> with <c>CommandParameter="{Binding}"</c>.
        /// </summary>
        [RelayCommand]
        private void Delete(TaskItemViewModel item)
        {
            item.PropertyChanged -= OnItemPropertyChanged;
            _ = _allTasks.Remove(item);
            Refresh();
        }

        /// <summary>
        /// Removes all completed tasks at once.
        /// </summary>
        [RelayCommand]
        private void ClearCompleted()
        {
            foreach (TaskItemViewModel t in _allTasks.Where(t => t.IsCompleted).ToList())
            {
                t.PropertyChanged -= OnItemPropertyChanged;
                _ = _allTasks.Remove(t);
            }
            Refresh();
        }

        // ---------------------------------------------------------------
        // Internal helpers
        // ---------------------------------------------------------------

        // Source-generated partial callback - fires when ActiveFilter changes.
        partial void OnActiveFilterChanged(FilterMode value)
        {
            Refresh();
        }

        // Propagate IsCompleted change on any item → rebuild filter + derived props.
        private void OnItemPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(TaskItemViewModel.IsCompleted))
            {
                Refresh();
            }
        }

        // Single rebuild path: Add/Delete/ClearCompleted and any IsCompleted toggle all funnel here.
        // We rebuild DisplayedTasks from _allTasks rather than mutating it in place so the filtered
        // view is always consistent in one step, then raise the derived StatusText/ProgressValue.
        private void Refresh()
        {
            IEnumerable<TaskItemViewModel> view = ActiveFilter switch
            {
                FilterMode.Pending => _allTasks.Where(t => !t.IsCompleted),
                FilterMode.Completed => _allTasks.Where(t => t.IsCompleted),
                FilterMode.All or _ => _allTasks,
            };
            DisplayedTasks = new ObservableCollection<TaskItemViewModel>(view);
            OnPropertyChanged(nameof(StatusText));
            OnPropertyChanged(nameof(ProgressValue));
        }
    }
}
