/*
 * Copyright 2026 Dan Cunningham
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

using System.Diagnostics.CodeAnalysis;
using System.Windows;
using System.Windows.Input;

namespace Fluence.Wpf.Controls
{
    /// <summary>
    /// The visual crumb generated by <see cref="BreadcrumbBar"/> for each item: a subtle
    /// button-like content host followed by a chevron separator that the default template
    /// hides on the last (current) crumb. Crumbs are keyboard focusable and activate through
    /// a mouse left-button release, Enter, or Space, raising <see cref="Click"/>.
    /// </summary>
    public class BreadcrumbBarItem : System.Windows.Controls.ContentControl
    {
        /// <summary>
        /// Initializes static members of the BreadcrumbBarItem class and overrides the default
        /// style metadata so the control picks up its themed template from Generic.xaml.
        /// </summary>
        static BreadcrumbBarItem()
        {
            DefaultStyleKeyProperty.OverrideMetadata(
                typeof(BreadcrumbBarItem),
                new FrameworkPropertyMetadata(typeof(BreadcrumbBarItem)));
        }

        private static readonly DependencyPropertyKey IsLastItemPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(IsLastItem),
                typeof(bool),
                typeof(BreadcrumbBarItem),
                new FrameworkPropertyMetadata(defaultValue: false));

        /// <summary>
        /// Identifies the <see cref="IsLastItem"/> dependency property.
        /// </summary>
        public static readonly DependencyProperty IsLastItemProperty =
            IsLastItemPropertyKey.DependencyProperty;

        /// <summary>
        /// Gets whether this crumb is the last (current) item of its owning
        /// <see cref="BreadcrumbBar"/>. The default template hides the chevron separator and
        /// switches to primary SemiBold typography while this is <see langword="true"/>.
        /// </summary>
        public bool IsLastItem
        {
            get => (bool)GetValue(IsLastItemProperty);
            internal set => SetValue(IsLastItemPropertyKey, value);
        }

        private static readonly DependencyPropertyKey IsPressedPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(IsPressed),
                typeof(bool),
                typeof(BreadcrumbBarItem),
                new FrameworkPropertyMetadata(defaultValue: false));

        /// <summary>
        /// Identifies the <see cref="IsPressed"/> dependency property.
        /// </summary>
        public static readonly DependencyProperty IsPressedProperty =
            IsPressedPropertyKey.DependencyProperty;

        /// <summary>
        /// Gets whether the crumb is currently pressed.
        /// </summary>
        public bool IsPressed
        {
            get => (bool)GetValue(IsPressedProperty);
            private set => SetValue(IsPressedPropertyKey, value);
        }

        /// <summary>
        /// Identifies the <see cref="Click"/> routed event.
        /// </summary>
        public static readonly RoutedEvent ClickEvent =
            EventManager.RegisterRoutedEvent(
                nameof(Click),
                RoutingStrategy.Bubble,
                typeof(RoutedEventHandler),
                typeof(BreadcrumbBarItem));

        /// <summary>
        /// Occurs when the crumb is activated by a mouse left-button release that began with
        /// a press inside the crumb bounds, or by the Enter or Space key while focused. The
        /// owning <see cref="BreadcrumbBar"/> aggregates this into
        /// <see cref="BreadcrumbBar.ItemClicked"/>.
        /// </summary>
        [SuppressMessage("Design", "S3908", Justification = "RoutedEventHandler is required by WPF's routed event infrastructure.")]
        public event RoutedEventHandler Click
        {
            add => AddHandler(ClickEvent, value);
            remove => RemoveHandler(ClickEvent, value);
        }

        /// <inheritdoc />
        protected override void OnKeyDown(KeyEventArgs e)
        {
            base.OnKeyDown(e);
            if (IsEnabled && e.Key is Key.Enter or Key.Space)
            {
                IsPressed = true;
                e.Handled = true;
            }
        }

        /// <inheritdoc />
        protected override void OnKeyUp(KeyEventArgs e)
        {
            base.OnKeyUp(e);
            if (IsEnabled && e.Key is Key.Enter or Key.Space)
            {
                bool wasPressed = IsPressed;
                IsPressed = false;
                if (wasPressed)
                {
                    RaiseEvent(new RoutedEventArgs(ClickEvent, this));
                }
                e.Handled = true;
            }
        }

        /// <inheritdoc />
        protected override void OnMouseLeftButtonDown(MouseButtonEventArgs e)
        {
            base.OnMouseLeftButtonDown(e);
            if (IsEnabled)
            {
                IsPressed = true;
                _ = CaptureMouse();
            }
        }

        /// <inheritdoc />
        protected override void OnMouseLeftButtonUp(MouseButtonEventArgs e)
        {
            base.OnMouseLeftButtonUp(e);
            bool wasPressed = IsPressed;
            if (wasPressed)
            {
                IsPressed = false;
                ReleaseMouseCapture();
            }
            if (wasPressed && IsEnabled)
            {
                RaiseEvent(new RoutedEventArgs(ClickEvent, this));
            }
        }

        /// <inheritdoc />
        protected override void OnLostMouseCapture(MouseEventArgs e)
        {
            base.OnLostMouseCapture(e);
            IsPressed = false;
        }

        /// <inheritdoc />
        protected override void OnMouseLeave(MouseEventArgs e)
        {
            base.OnMouseLeave(e);
            if (IsPressed)
            {
                IsPressed = false;
                ReleaseMouseCapture();
            }
        }
    }
}
