<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <RootNamespace>PSADT.UserInterface.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PSADT.UserInterface\PSADT.UserInterface.csproj" />
  </ItemGroup>

</Project>
