namespace PSADT.Interop
{
    /// <summary>
    /// Represents the Windows message identifiers used in the Windows API for handling various system and application
    /// events.
    /// </summary>
    /// <remarks>The <see cref="WINDOW_MESSAGE"/> enumeration defines a comprehensive set of message constants
    /// that are used by the Windows operating system to communicate with applications. These messages cover a wide
    /// range of events, including window creation, destruction, input handling, and system commands. Each message is
    /// associated with a unique identifier, which is used to determine the type of event or action that has occurred. 
    /// This enumeration is primarily used in the context of Windows message loops, where applications process incoming
    /// messages to perform appropriate actions. The messages are categorized into several groups, such as core window
    /// messages, non-client area messages, keyboard and input method editor (IME) messages, dialog and command
    /// messages, mouse messages, and more. Developers typically handle these messages in a window procedure function,
    /// which processes each message and executes the corresponding application logic. Understanding and correctly
    /// handling these messages is crucial for developing responsive and well-behaved Windows applications.</remarks>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "These values are precisely as they're defined in the Win32 API.")]
    internal enum WINDOW_MESSAGE : uint
    {
        // Core Window Messages (0x0000–0x0055).
        WM_NULL = Windows.Win32.PInvoke.WM_NULL,
        WM_CREATE = Windows.Win32.PInvoke.WM_CREATE,
        WM_DESTROY = Windows.Win32.PInvoke.WM_DESTROY,
        WM_MOVE = Windows.Win32.PInvoke.WM_MOVE,
        WM_SIZE = Windows.Win32.PInvoke.WM_SIZE,
        WM_ACTIVATE = Windows.Win32.PInvoke.WM_ACTIVATE,
        WM_SETFOCUS = Windows.Win32.PInvoke.WM_SETFOCUS,
        WM_KILLFOCUS = Windows.Win32.PInvoke.WM_KILLFOCUS,
        WM_ENABLE = Windows.Win32.PInvoke.WM_ENABLE,
        WM_SETREDRAW = Windows.Win32.PInvoke.WM_SETREDRAW,
        WM_SETTEXT = Windows.Win32.PInvoke.WM_SETTEXT,
        WM_GETTEXT = Windows.Win32.PInvoke.WM_GETTEXT,
        WM_GETTEXTLENGTH = Windows.Win32.PInvoke.WM_GETTEXTLENGTH,
        WM_PAINT = Windows.Win32.PInvoke.WM_PAINT,
        WM_CLOSE = Windows.Win32.PInvoke.WM_CLOSE,
        WM_QUERYENDSESSION = Windows.Win32.PInvoke.WM_QUERYENDSESSION,
        WM_QUIT = Windows.Win32.PInvoke.WM_QUIT,
        WM_QUERYOPEN = Windows.Win32.PInvoke.WM_QUERYOPEN,
        WM_ERASEBKGND = Windows.Win32.PInvoke.WM_ERASEBKGND,
        WM_SYSCOLORCHANGE = Windows.Win32.PInvoke.WM_SYSCOLORCHANGE,
        WM_ENDSESSION = Windows.Win32.PInvoke.WM_ENDSESSION,
        WM_SHOWWINDOW = Windows.Win32.PInvoke.WM_SHOWWINDOW,
        WM_CTLCOLOR = Windows.Win32.PInvoke.WM_CTLCOLOR,
        WM_WININICHANGE = Windows.Win32.PInvoke.WM_WININICHANGE,
        WM_SETTINGCHANGE = Windows.Win32.PInvoke.WM_SETTINGCHANGE,
        WM_DEVMODECHANGE = Windows.Win32.PInvoke.WM_DEVMODECHANGE,
        WM_ACTIVATEAPP = Windows.Win32.PInvoke.WM_ACTIVATEAPP,
        WM_FONTCHANGE = Windows.Win32.PInvoke.WM_FONTCHANGE,
        WM_TIMECHANGE = Windows.Win32.PInvoke.WM_TIMECHANGE,
        WM_CANCELMODE = Windows.Win32.PInvoke.WM_CANCELMODE,
        WM_SETCURSOR = Windows.Win32.PInvoke.WM_SETCURSOR,
        WM_MOUSEACTIVATE = Windows.Win32.PInvoke.WM_MOUSEACTIVATE,
        WM_CHILDACTIVATE = Windows.Win32.PInvoke.WM_CHILDACTIVATE,
        WM_QUEUESYNC = Windows.Win32.PInvoke.WM_QUEUESYNC,
        WM_GETMINMAXINFO = Windows.Win32.PInvoke.WM_GETMINMAXINFO,
        WM_PAINTICON = Windows.Win32.PInvoke.WM_PAINTICON,
        WM_ICONERASEBKGND = Windows.Win32.PInvoke.WM_ICONERASEBKGND,
        WM_NEXTDLGCTL = Windows.Win32.PInvoke.WM_NEXTDLGCTL,
        WM_SPOOLERSTATUS = Windows.Win32.PInvoke.WM_SPOOLERSTATUS,
        WM_DRAWITEM = Windows.Win32.PInvoke.WM_DRAWITEM,
        WM_MEASUREITEM = Windows.Win32.PInvoke.WM_MEASUREITEM,
        WM_DELETEITEM = Windows.Win32.PInvoke.WM_DELETEITEM,
        WM_VKEYTOITEM = Windows.Win32.PInvoke.WM_VKEYTOITEM,
        WM_CHARTOITEM = Windows.Win32.PInvoke.WM_CHARTOITEM,
        WM_SETFONT = Windows.Win32.PInvoke.WM_SETFONT,
        WM_GETFONT = Windows.Win32.PInvoke.WM_GETFONT,
        WM_SETHOTKEY = Windows.Win32.PInvoke.WM_SETHOTKEY,
        WM_GETHOTKEY = Windows.Win32.PInvoke.WM_GETHOTKEY,
        WM_QUERYDRAGICON = Windows.Win32.PInvoke.WM_QUERYDRAGICON,
        WM_COMPAREITEM = Windows.Win32.PInvoke.WM_COMPAREITEM,
        WM_COMPACTING = Windows.Win32.PInvoke.WM_COMPACTING,
        WM_WINDOWPOSCHANGING = Windows.Win32.PInvoke.WM_WINDOWPOSCHANGING,
        WM_WINDOWPOSCHANGED = Windows.Win32.PInvoke.WM_WINDOWPOSCHANGED,
        WM_POWER = Windows.Win32.PInvoke.WM_POWER,
        WM_COPYDATA = Windows.Win32.PInvoke.WM_COPYDATA,
        WM_CANCELJOURNAL = Windows.Win32.PInvoke.WM_CANCELJOURNAL,
        WM_NOTIFY = Windows.Win32.PInvoke.WM_NOTIFY,
        WM_INPUTLANGCHANGEREQUEST = Windows.Win32.PInvoke.WM_INPUTLANGCHANGEREQUEST,
        WM_INPUTLANGCHANGE = Windows.Win32.PInvoke.WM_INPUTLANGCHANGE,
        WM_TCARD = Windows.Win32.PInvoke.WM_TCARD,
        WM_HELP = Windows.Win32.PInvoke.WM_HELP,
        WM_USERCHANGED = Windows.Win32.PInvoke.WM_USERCHANGED,
        WM_NOTIFYFORMAT = Windows.Win32.PInvoke.WM_NOTIFYFORMAT,

        // Non‑Client Area Messages (0x0081–0x00A9).
        WM_NCCREATE = Windows.Win32.PInvoke.WM_NCCREATE,
        WM_NCDESTROY = Windows.Win32.PInvoke.WM_NCDESTROY,
        WM_NCCALCSIZE = Windows.Win32.PInvoke.WM_NCCALCSIZE,
        WM_NCHITTEST = Windows.Win32.PInvoke.WM_NCHITTEST,
        WM_NCPAINT = Windows.Win32.PInvoke.WM_NCPAINT,
        WM_NCACTIVATE = Windows.Win32.PInvoke.WM_NCACTIVATE,
        WM_GETDLGCODE = Windows.Win32.PInvoke.WM_GETDLGCODE,
        WM_NCMOUSEMOVE = Windows.Win32.PInvoke.WM_NCMOUSEMOVE,
        WM_NCLBUTTONDOWN = Windows.Win32.PInvoke.WM_NCLBUTTONDOWN,
        WM_NCLBUTTONUP = Windows.Win32.PInvoke.WM_NCLBUTTONUP,
        WM_NCLBUTTONDBLCLK = Windows.Win32.PInvoke.WM_NCLBUTTONDBLCLK,
        WM_NCRBUTTONDOWN = Windows.Win32.PInvoke.WM_NCRBUTTONDOWN,
        WM_NCRBUTTONUP = Windows.Win32.PInvoke.WM_NCRBUTTONUP,
        WM_NCRBUTTONDBLCLK = Windows.Win32.PInvoke.WM_NCRBUTTONDBLCLK,
        WM_NCMBUTTONDOWN = Windows.Win32.PInvoke.WM_NCMBUTTONDOWN,
        WM_NCMBUTTONUP = Windows.Win32.PInvoke.WM_NCMBUTTONUP,
        WM_NCMBUTTONDBLCLK = Windows.Win32.PInvoke.WM_NCMBUTTONDBLCLK,

        // Keyboard & IME Messages (0x0100–0x010F).
        WM_KEYFIRST = Windows.Win32.PInvoke.WM_KEYFIRST,
        WM_KEYDOWN = Windows.Win32.PInvoke.WM_KEYDOWN,
        WM_KEYUP = Windows.Win32.PInvoke.WM_KEYUP,
        WM_CHAR = Windows.Win32.PInvoke.WM_CHAR,
        WM_DEADCHAR = Windows.Win32.PInvoke.WM_DEADCHAR,
        WM_SYSKEYDOWN = Windows.Win32.PInvoke.WM_SYSKEYDOWN,
        WM_SYSKEYUP = Windows.Win32.PInvoke.WM_SYSKEYUP,
        WM_SYSCHAR = Windows.Win32.PInvoke.WM_SYSCHAR,
        WM_SYSDEADCHAR = Windows.Win32.PInvoke.WM_SYSDEADCHAR,
        WM_KEYLAST = Windows.Win32.PInvoke.WM_KEYLAST,
        WM_IME_STARTCOMPOSITION = Windows.Win32.PInvoke.WM_IME_STARTCOMPOSITION,
        WM_IME_ENDCOMPOSITION = Windows.Win32.PInvoke.WM_IME_ENDCOMPOSITION,
        WM_IME_COMPOSITION = Windows.Win32.PInvoke.WM_IME_COMPOSITION,
        WM_IME_KEYLAST = Windows.Win32.PInvoke.WM_IME_KEYLAST,

        // Dialog, Command & System‑Control (0x0110–0x0138).
        WM_INITDIALOG = Windows.Win32.PInvoke.WM_INITDIALOG,
        WM_COMMAND = Windows.Win32.PInvoke.WM_COMMAND,
        WM_SYSCOMMAND = Windows.Win32.PInvoke.WM_SYSCOMMAND,
        WM_TIMER = Windows.Win32.PInvoke.WM_TIMER,
        WM_HSCROLL = Windows.Win32.PInvoke.WM_HSCROLL,
        WM_VSCROLL = Windows.Win32.PInvoke.WM_VSCROLL,
        WM_INITMENU = Windows.Win32.PInvoke.WM_INITMENU,
        WM_INITMENUPOPUP = Windows.Win32.PInvoke.WM_INITMENUPOPUP,
        WM_MENUSELECT = Windows.Win32.PInvoke.WM_MENUSELECT,
        WM_MENUCHAR = Windows.Win32.PInvoke.WM_MENUCHAR,
        WM_ENTERIDLE = Windows.Win32.PInvoke.WM_ENTERIDLE,
        WM_CTLCOLORMSGBOX = Windows.Win32.PInvoke.WM_CTLCOLORMSGBOX,
        WM_CTLCOLOREDIT = Windows.Win32.PInvoke.WM_CTLCOLOREDIT,
        WM_CTLCOLORLISTBOX = Windows.Win32.PInvoke.WM_CTLCOLORLISTBOX,
        WM_CTLCOLORBTN = Windows.Win32.PInvoke.WM_CTLCOLORBTN,
        WM_CTLCOLORDLG = Windows.Win32.PInvoke.WM_CTLCOLORDLG,
        WM_CTLCOLORSCROLLBAR = Windows.Win32.PInvoke.WM_CTLCOLORSCROLLBAR,
        WM_CTLCOLORSTATIC = Windows.Win32.PInvoke.WM_CTLCOLORSTATIC,

        // Mouse Messages (0x0200–0x020E).
        WM_MOUSEFIRST = Windows.Win32.PInvoke.WM_MOUSEFIRST,
        WM_MOUSEMOVE = Windows.Win32.PInvoke.WM_MOUSEMOVE,
        WM_LBUTTONDOWN = Windows.Win32.PInvoke.WM_LBUTTONDOWN,
        WM_LBUTTONUP = Windows.Win32.PInvoke.WM_LBUTTONUP,
        WM_LBUTTONDBLCLK = Windows.Win32.PInvoke.WM_LBUTTONDBLCLK,
        WM_RBUTTONDOWN = Windows.Win32.PInvoke.WM_RBUTTONDOWN,
        WM_RBUTTONUP = Windows.Win32.PInvoke.WM_RBUTTONUP,
        WM_RBUTTONDBLCLK = Windows.Win32.PInvoke.WM_RBUTTONDBLCLK,
        WM_MBUTTONDOWN = Windows.Win32.PInvoke.WM_MBUTTONDOWN,
        WM_MBUTTONUP = Windows.Win32.PInvoke.WM_MBUTTONUP,
        WM_MBUTTONDBLCLK = Windows.Win32.PInvoke.WM_MBUTTONDBLCLK,
        WM_MOUSEWHEEL = Windows.Win32.PInvoke.WM_MOUSEWHEEL,
        WM_MOUSEHWHEEL = Windows.Win32.PInvoke.WM_MOUSEHWHEEL,

        // Other Window & MDI Notifications (0x0210–0x0234).
        WM_PARENTNOTIFY = Windows.Win32.PInvoke.WM_PARENTNOTIFY,
        WM_ENTERMENULOOP = Windows.Win32.PInvoke.WM_ENTERMENULOOP,
        WM_EXITMENULOOP = Windows.Win32.PInvoke.WM_EXITMENULOOP,
        WM_NEXTMENU = Windows.Win32.PInvoke.WM_NEXTMENU,
        WM_SIZING = Windows.Win32.PInvoke.WM_SIZING,
        WM_CAPTURECHANGED = Windows.Win32.PInvoke.WM_CAPTURECHANGED,
        WM_MOVING = Windows.Win32.PInvoke.WM_MOVING,
        WM_POWERBROADCAST = Windows.Win32.PInvoke.WM_POWERBROADCAST,
        WM_DEVICECHANGE = Windows.Win32.PInvoke.WM_DEVICECHANGE,
        WM_MDICREATE = Windows.Win32.PInvoke.WM_MDICREATE,
        WM_MDIDESTROY = Windows.Win32.PInvoke.WM_MDIDESTROY,
        WM_MDIACTIVATE = Windows.Win32.PInvoke.WM_MDIACTIVATE,
        WM_MDIRESTORE = Windows.Win32.PInvoke.WM_MDIRESTORE,
        WM_MDINEXT = Windows.Win32.PInvoke.WM_MDINEXT,
        WM_MDIMAXIMIZE = Windows.Win32.PInvoke.WM_MDIMAXIMIZE,
        WM_MDITILE = Windows.Win32.PInvoke.WM_MDITILE,
        WM_MDICASCADE = Windows.Win32.PInvoke.WM_MDICASCADE,
        WM_MDIICONARRANGE = Windows.Win32.PInvoke.WM_MDIICONARRANGE,
        WM_MDIGETACTIVE = Windows.Win32.PInvoke.WM_MDIGETACTIVE,
        WM_MDISETMENU = Windows.Win32.PInvoke.WM_MDISETMENU,
        WM_ENTERSIZEMOVE = Windows.Win32.PInvoke.WM_ENTERSIZEMOVE,
        WM_EXITSIZEMOVE = Windows.Win32.PInvoke.WM_EXITSIZEMOVE,
        WM_DROPFILES = Windows.Win32.PInvoke.WM_DROPFILES,
        WM_MDIREFRESHMENU = Windows.Win32.PInvoke.WM_MDIREFRESHMENU,

        // IME Control & Hover/Leave (0x0281–0x02A3).
        WM_IME_SETCONTEXT = Windows.Win32.PInvoke.WM_IME_SETCONTEXT,
        WM_IME_NOTIFY = Windows.Win32.PInvoke.WM_IME_NOTIFY,
        WM_IME_CONTROL = Windows.Win32.PInvoke.WM_IME_CONTROL,
        WM_IME_COMPOSITIONFULL = Windows.Win32.PInvoke.WM_IME_COMPOSITIONFULL,
        WM_IME_SELECT = Windows.Win32.PInvoke.WM_IME_SELECT,
        WM_IME_CHAR = Windows.Win32.PInvoke.WM_IME_CHAR,
        WM_IME_KEYDOWN = Windows.Win32.PInvoke.WM_IME_KEYDOWN,
        WM_IME_KEYUP = Windows.Win32.PInvoke.WM_IME_KEYUP,
        WM_MOUSEHOVER = Windows.Win32.PInvoke.WM_MOUSEHOVER,
        WM_NCMOUSELEAVE = Windows.Win32.PInvoke.WM_NCMOUSELEAVE,
        WM_MOUSELEAVE = Windows.Win32.PInvoke.WM_MOUSELEAVE,

        // Clipboard & Printing (0x0300–0x0318).
        WM_CUT = Windows.Win32.PInvoke.WM_CUT,
        WM_COPY = Windows.Win32.PInvoke.WM_COPY,
        WM_PASTE = Windows.Win32.PInvoke.WM_PASTE,
        WM_CLEAR = Windows.Win32.PInvoke.WM_CLEAR,
        WM_UNDO = Windows.Win32.PInvoke.WM_UNDO,
        WM_RENDERFORMAT = Windows.Win32.PInvoke.WM_RENDERFORMAT,
        WM_RENDERALLFORMATS = Windows.Win32.PInvoke.WM_RENDERALLFORMATS,
        WM_DESTROYCLIPBOARD = Windows.Win32.PInvoke.WM_DESTROYCLIPBOARD,
        WM_DRAWCLIPBOARD = Windows.Win32.PInvoke.WM_DRAWCLIPBOARD,
        WM_PAINTCLIPBOARD = Windows.Win32.PInvoke.WM_PAINTCLIPBOARD,
        WM_VSCROLLCLIPBOARD = Windows.Win32.PInvoke.WM_VSCROLLCLIPBOARD,
        WM_SIZECLIPBOARD = Windows.Win32.PInvoke.WM_SIZECLIPBOARD,
        WM_ASKCBFORMATNAME = Windows.Win32.PInvoke.WM_ASKCBFORMATNAME,
        WM_CHANGECBCHAIN = Windows.Win32.PInvoke.WM_CHANGECBCHAIN,
        WM_HSCROLLCLIPBOARD = Windows.Win32.PInvoke.WM_HSCROLLCLIPBOARD,
        WM_QUERYNEWPALETTE = Windows.Win32.PInvoke.WM_QUERYNEWPALETTE,
        WM_PALETTEISCHANGING = Windows.Win32.PInvoke.WM_PALETTEISCHANGING,
        WM_PALETTECHANGED = Windows.Win32.PInvoke.WM_PALETTECHANGED,
        WM_HOTKEY = Windows.Win32.PInvoke.WM_HOTKEY,
        WM_PRINT = Windows.Win32.PInvoke.WM_PRINT,
        WM_PRINTCLIENT = Windows.Win32.PInvoke.WM_PRINTCLIENT,

        // Handheld, Pen & DDE (0x0358–0x03E8).
        WM_HANDHELDFIRST = Windows.Win32.PInvoke.WM_HANDHELDFIRST,
        WM_HANDHELDLAST = Windows.Win32.PInvoke.WM_HANDHELDLAST,
        WM_PENWINFIRST = Windows.Win32.PInvoke.WM_PENWINFIRST,
        WM_PENWINLAST = Windows.Win32.PInvoke.WM_PENWINLAST,
        WM_DDE_FIRST = Windows.Win32.PInvoke.WM_DDE_FIRST,
        WM_DDE_INITIATE = Windows.Win32.PInvoke.WM_DDE_INITIATE,
        WM_DDE_TERMINATE = Windows.Win32.PInvoke.WM_DDE_TERMINATE,
        WM_DDE_ADVISE = Windows.Win32.PInvoke.WM_DDE_ADVISE,
        WM_DDE_UNADVISE = Windows.Win32.PInvoke.WM_DDE_UNADVISE,
        WM_DDE_ACK = Windows.Win32.PInvoke.WM_DDE_ACK,
        WM_DDE_DATA = Windows.Win32.PInvoke.WM_DDE_DATA,
        WM_DDE_REQUEST = Windows.Win32.PInvoke.WM_DDE_REQUEST,
        WM_DDE_POKE = Windows.Win32.PInvoke.WM_DDE_POKE,
        WM_DDE_EXECUTE = Windows.Win32.PInvoke.WM_DDE_EXECUTE,
        WM_DDE_LAST = Windows.Win32.PInvoke.WM_DDE_LAST,

        // Private & Application‑Defined Ranges.
        WM_USER = Windows.Win32.PInvoke.WM_USER,
        WM_APP = Windows.Win32.PInvoke.WM_APP,
    }
}
