//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNKORE.UI.WPF.Modern {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iNKORE.UI.WPF.Modern.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string AppBarMoreButtonClosedToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonClosedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More app bar.
        /// </summary>
        internal static string AppBarMoreButtonName {
            get {
                return ResourceManager.GetString("AppBarMoreButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See less.
        /// </summary>
        internal static string AppBarMoreButtonOpenToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreMenuItemLabel {
            get {
                return ResourceManager.GetString("IgnoreMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofing.
        /// </summary>
        internal static string ProofingMenuItemLabel {
            get {
                return ResourceManager.GetString("ProofingMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tab.
        /// </summary>
        internal static string TabViewAddButtonTooltip {
            get {
                return ResourceManager.GetString("TabViewAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab (Ctrl + F4).
        /// </summary>
        internal static string TabViewCloseButtonTooltipWithKA {
            get {
                return ResourceManager.GetString("TabViewCloseButtonTooltipWithKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll tab list backward.
        /// </summary>
        internal static string TabViewScrollDecreaseButtonTooltip {
            get {
                return ResourceManager.GetString("TabViewScrollDecreaseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll tab list forward.
        /// </summary>
        internal static string TabViewScrollIncreaseButtonTooltip {
            get {
                return ResourceManager.GetString("TabViewScrollIncreaseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold the selected text.
        /// </summary>
        internal static string TextCommandDescriptionBold {
            get {
                return ResourceManager.GetString("TextCommandDescriptionBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selected content to the clipboard.
        /// </summary>
        internal static string TextCommandDescriptionCopy {
            get {
                return ResourceManager.GetString("TextCommandDescriptionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected content and put it on the clipboard.
        /// </summary>
        internal static string TextCommandDescriptionCut {
            get {
                return ResourceManager.GetString("TextCommandDescriptionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italicize the selected text.
        /// </summary>
        internal static string TextCommandDescriptionItalic {
            get {
                return ResourceManager.GetString("TextCommandDescriptionItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the contents of the clipboard at the current location.
        /// </summary>
        internal static string TextCommandDescriptionPaste {
            get {
                return ResourceManager.GetString("TextCommandDescriptionPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the most recently undone action.
        /// </summary>
        internal static string TextCommandDescriptionRedo {
            get {
                return ResourceManager.GetString("TextCommandDescriptionRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all content.
        /// </summary>
        internal static string TextCommandDescriptionSelectAll {
            get {
                return ResourceManager.GetString("TextCommandDescriptionSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline the selected text.
        /// </summary>
        internal static string TextCommandDescriptionUnderline {
            get {
                return ResourceManager.GetString("TextCommandDescriptionUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse the most recent action.
        /// </summary>
        internal static string TextCommandDescriptionUndo {
            get {
                return ResourceManager.GetString("TextCommandDescriptionUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyBold {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyCopy {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyCut {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyItalic {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyPaste {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyRedo {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeySelectAll {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeySelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyUnderline {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string TextCommandKeyboardAcceleratorKeyUndo {
            get {
                return ResourceManager.GetString("TextCommandKeyboardAcceleratorKeyUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string TextCommandLabelBold {
            get {
                return ResourceManager.GetString("TextCommandLabelBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TextCommandLabelCopy {
            get {
                return ResourceManager.GetString("TextCommandLabelCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string TextCommandLabelCut {
            get {
                return ResourceManager.GetString("TextCommandLabelCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string TextCommandLabelItalic {
            get {
                return ResourceManager.GetString("TextCommandLabelItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string TextCommandLabelPaste {
            get {
                return ResourceManager.GetString("TextCommandLabelPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string TextCommandLabelRedo {
            get {
                return ResourceManager.GetString("TextCommandLabelRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string TextCommandLabelSelectAll {
            get {
                return ResourceManager.GetString("TextCommandLabelSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string TextCommandLabelUnderline {
            get {
                return ResourceManager.GetString("TextCommandLabelUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string TextCommandLabelUndo {
            get {
                return ResourceManager.GetString("TextCommandLabelUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
    }
}
