/*
 * Copyright 2026 Dan Cunningham
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

using System.Runtime.InteropServices;

namespace Fluence.Wpf.Native
{
    /// <summary>
    /// Mirrors the undocumented <c language="csharp">ACCENT_POLICY</c> structure passed to
    /// <c language="csharp">SetWindowCompositionAttribute</c> under <c language="csharp">WCA_ACCENT_POLICY</c>. This is the Windows 10
    /// mechanism behind the legacy acrylic and blur-behind effects; it has no public SDK header, so
    /// it cannot be generated by CsWin32 and is declared by hand here. Field order and types must
    /// match the native layout exactly, and the struct must stay blittable so it can be pinned
    /// through a <see cref="GCHandle"/>.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal struct ACCENT_POLICY
    {
        /// <summary>
        /// The accent state, one of the <c>ACCENT_*</c> constants on
        /// <see cref="NativeMethods"/>.
        /// </summary>
        public int AccentState;

        /// <summary>
        /// The accent flags. Fluence always passes zero: the documented-by-reverse-engineering
        /// flag values only select which window edges the accent draws its border on, and Fluence
        /// paints its own border from the WPF template.
        /// </summary>
        public uint AccentFlags;

        /// <summary>
        /// The tint color as a packed <c>0xAABBGGRR</c> value. Ignored by the accent states that
        /// do not tint, notably <c>ACCENT_ENABLE_BLURBEHIND</c>.
        /// </summary>
        public uint GradientColor;

        /// <summary>
        /// The animation id. Unused by every accent state Fluence sets; always zero.
        /// </summary>
        public uint AnimationId;
    }
}
